name: CI
on: 
  pull_request:
    branches:
      - main

jobs:
  build_ios:
    name: Build  Flutter (iOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        channel: "stable"
      -run: flutter pub get 
      -run: flutter clean
      -run: flutter build ios --no-codesign
      
  build_appbundle:
    name: Build  Flutter (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      with:
        channel: "stable"
      -run: flutter pub get 
      -run: flutter clean
      -run: flutter build appbundle
